language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.1

before_install:
  - rm .gemfiles/Gemfile.rspec.lock || true
  - rm .gemfiles/Gemfile.ruby187.rspec.lock || true

gemfile:
  - .gemfiles/Gemfile.rspec
  - .gemfiles/Gemfile.ruby187.rspec
  - .gemfiles/Gemfile.ruby193.rspec

script:
 - "bundle exec rake spec SPEC_OPTS='--format documentation'"

env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.0.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 4.5.0"
  - PUPPET_VERSION="~> 4.6.0"
  - PUPPET_VERSION="~> 4.7.0"
  - PUPPET_VERSION="~> 4.8.0"

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: .gemfiles/Gemfile.rspec
    - rvm: 1.8.7
      gemfile: .gemfiles/Gemfile.ruby193.rspec
    - rvm: 1.9.3
      gemfile: .gemfiles/Gemfile.ruby187.rspec
    - rvm: 1.9.3
      gemfile: .gemfiles/Gemfile.rspec
    - rvm: 2.0.0
      gemfile: .gemfiles/Gemfile.ruby187.rspec
    - rvm: 2.0.0
      gemfile: .gemfiles/Gemfile.ruby193.rspec
    - rvm: 2.1.1
      gemfile: .gemfiles/Gemfile.ruby187.rspec
    - rvm: 2.1.1
      gemfile: .gemfiles/Gemfile.ruby193.rspec
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 4.0.0"
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 4.1.0"
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 4.2.0"
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 4.3.0"
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 4.4.0"
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 4.5.0"
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 4.6.0"
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 4.7.0"
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 4.8.0"
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.0"
    - rvm: 2.1.1
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.1.1
      env: PUPPET_VERSION="~> 3.0.0"
    - rvm: 2.1.1
      env: PUPPET_VERSION="~> 3.1.0"
    - rvm: 2.1.1
      env: PUPPET_VERSION="~> 3.2.0"
    - rvm: 2.1.1
      env: PUPPET_VERSION="~> 3.3.0"
    - rvm: 2.1.1
      env: PUPPET_VERSION="~> 3.4.0"
